<a href="https://colab.research.google.com/github/everestso/Summer22/blob/main/Tensor1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf 
x = tf.constant("Hello World") 
tf.print(x) #will print out "Hello World" 
print(x)

Hello World
tf.Tensor(b'Hello World', shape=(), dtype=string)


In [2]:
x = tf.constant(2.0) 
z = tf.Variable(0.0) 
comp=tf.add(x,z) 
tf.print(comp)
# Prints out 5.0 
z = 3
comp=tf.add(x,z)
tf.print(comp)


2
5


In [3]:
tf.random.set_seed(5)
bt = tf.random.normal([10], stddev=.1) 
b = tf.Variable(bt) 
W = tf.Variable(tf.random.normal([784,10],stddev=.1)) 
tf.print(bt.shape,'\n', bt)
tf.print(b.shape,'\n', b)
tf.print(W.shape,'\n', W)

TensorShape([10]) 
 [-0.0180306658 -0.0950286314 -0.00396404928 ... -0.00889995322 0.244886979 0.0762508]
TensorShape([10]) 
 [-0.0180306658 -0.0950286314 -0.00396404928 ... -0.00889995322 0.244886979 0.0762508]
TensorShape([784, 10]) 
 [[0.0226528645 0.0810655281 0.074660942 ... 0.134644642 -0.102107339 0.000945170817]
 [0.115963258 0.211279511 -0.0712643936 ... -0.097436361 0.00409729686 -0.0490662046]
 [-0.154450819 -0.250504017 0.149005458 ... -0.115962528 -0.098184742 0.144222826]
 ...
 [-0.0699647665 -0.0683866739 -0.00309383939 ... -0.0141383661 -0.19987841 0.0107175102]
 [-0.122395948 -0.0329876244 0.0949689075 ... -0.011294893 -0.153111294 -0.073111169]
 [0.102189317 -0.0176626984 -0.00608549872 ... -0.139482155 0.0312592201 0.0325849429]]


In [5]:
import numpy as np
batchSz=10
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

W=tf.Variable(tf.random.normal([784,10],stddev=.1))
b=tf.random.normal([10],stddev=.1)

img=tf.Variable(tf.random.normal([batchSz,784],stddev=.1))
ans=tf.Variable(tf.zeros(shape=([batchSz,10])))

#prbs=tf.nn.softmax(tf.matmul(img,W)+b)

i = 0

img = tf.reshape(x_train[i:i+batchSz,:], (batchSz, 28*28))
img = tf.cast(img, tf.float32)/255.0
anss = y_train[i:i+batchSz]
prbs = tf.nn.softmax(tf.matmul(img, W) + b) 

print (prbs)
print (anss)

tf.Tensor(
[[0.13488813 0.07422982 0.07347591 0.0381734  0.03884091 0.15403995
  0.06959417 0.15560423 0.07150591 0.1896476 ]
 [0.20175889 0.03580334 0.06355184 0.02125184 0.08100542 0.11471821
  0.2736313  0.03162998 0.12441325 0.05223599]
 [0.16488245 0.02682832 0.09540796 0.0356078  0.16868185 0.03107219
  0.29938677 0.05617866 0.06528474 0.05666935]
 [0.13848537 0.04693684 0.03643512 0.08763347 0.05690173 0.09903066
  0.09952462 0.12149523 0.26732904 0.04622789]
 [0.19999617 0.04327204 0.05486573 0.01816633 0.15108438 0.02233549
  0.21976316 0.03628184 0.22608748 0.02814735]
 [0.08240918 0.02133325 0.00962957 0.02922455 0.03755412 0.05783606
  0.5255081  0.04500192 0.16349572 0.02800758]
 [0.11677734 0.0543555  0.17814967 0.05097408 0.04706721 0.04507262
  0.0530569  0.10960533 0.28284493 0.06209651]
 [0.39547458 0.11098238 0.04843941 0.02846079 0.02878258 0.05011274
  0.04622936 0.10311633 0.05162881 0.13677299]
 [0.12095381 0.03865198 0.09684891 0.07014885 0.08407918 0.04459606
 

# New Example

In [16]:
import tensorflow as tf
x = tf.Variable(1.)
with tf.GradientTape() as tape:
    y = 2 * x**3 + 3*x + 4
grad_of_y_wrt_x = tape.gradient(y, x)
print (grad_of_y_wrt_x)

tf.Tensor(9.0, shape=(), dtype=float32)


In [19]:
#x = tf.Variable(tf.random.uniform((2, 2)))
x = tf.Variable([[0.0, 1.0], [2.0, 3.0]])
with tf.GradientTape() as tape:
    y = 2 * x**3 + 3*x + 4
grad_of_y_wrt_x = tape.gradient(y, x)
print  (grad_of_y_wrt_x)

tf.Tensor(
[[ 3.  9.]
 [27. 57.]], shape=(2, 2), dtype=float32)


In [20]:
W = tf.Variable(tf.random.uniform((2, 2)))
b = tf.Variable(tf.zeros((2,)))
x = tf.random.uniform((2, 2))
with tf.GradientTape() as tape:
    y = tf.matmul(x, W) + b
grad_of_y_wrt_W_and_b = tape.gradient(y, [W, b])